### ISSUE TITLE
Reasoner error?

### ISSUE THREAD

**Issue by constnick** [mdesalvo/OWLSharp#24]
Hi Marco,
here are the steps:
1. The `ontology` is made from the graph:
``` 
ex:DescendantOf rdf:type owl:ObjectProperty .
ex:ParentOf rdf:type owl:ObjectProperty .

ex:ParentOf rdfs:subPropertyOf [ owl:inverseOf ex:DescendantOf ] .

ex:iJunior rdf:type owl:NamedIndividual .
ex:iMajor rdf:type owl:NamedIndividual .
ex:iMajor ex:ParentOf ex:iJunior .
```
2. The reasoner with single rule is applied to `ontology`:
```c#
var report = new OWLReasoner().AddRule(OWLEnums.OWLReasonerRules.PropertyEntailment).ApplyToOntology(ontology);
```
3. The following error occurs:
`Cannot create RDFTriple because given "pred" parameter is a blank resource`

Other well-known reasoners handle this properly.

**Comment by mdesalvo** [comment]
Hi constnick,
thanks as usual for the attention to the library and for your detailed reports!

This is an error of the reasoner, which is not smart enough to detect the pattern "ex:something ex:predicate [ owl:inverseOf ex:somethingInverse ]" and so tries to build the inference with the blank predicate instead of the indirectly referred one (ex:somethingInverse).

I'll patch this rule, if you find other parts of the library which are tricked by this syntax feel free to signal as usual.

Regards,
Marco

**Comment by mdesalvo** [comment]
Checked-in fixes in bd56416:

- Discard blank properties during "PropertyEntailment" reasoner rule, so that it will not crash anymore when encountering blank candidate properties coming from OWL2-full anonymous inline property expressions
- Recognize OWL2-full anonymous inline property expressions during owl:inverseOf computation, so that "InverseOfEntailment" reasoner rule will be able to infer "ex:iJunior ex:DescendantOf ex:iMajor"

**Comment by mdesalvo** [comment]
Hi @constnick,
as you are an expert ontologist, can you kindly explain me the purpose of the syntax:

```
ex:ParentOf rdfs:subPropertyOf [ owl:inverseOf ex:DescendantOf ] .
```

What is the advantage against an explicit statement:
```
ex:ParentOf owl:inverseOf ex:DescendantOf
```

Can this also exist in equivalency way:

```
ex:ParentOf owl:equivalentProperty [ owl:inverseOf ex:DescendantOf ] .
```

Thanks,
Marco

**Comment by constnick** [comment]
`ex:ParentOf owl:inverseOf ex:DescendantOf` — it is a wrong assertion within the model. 
The inverse of `DescendantOf ` is somethin like `AncestorOf`, and `ParentOf ` is the subproperty of it.
Of course we can create the inverse property explicitly, but it is usually inconvenient to create inverse of every property for possible rare usage.

**Comment by mdesalvo** [comment]
Thanks for the clarification.

I checked on Protege with Pellet and HermiT reasoners emitting "ex:iJunior ex:DescendantOf ex:iMajor" inference. I confirm that now our rule named "InverseOfEntailment" is compliant. Expect the updated version soon.

Regards,
Marco
